[package]
name = "justcxx-macro"
version = "0.2.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.114", features = ["full", "extra-traits", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
justcxx-build = { path = "../build" }